---
- hosts: all
  become: true

  tasks:
    - name: Setup passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Update apt and install required system packages
      apt:
        pkg:
          - curl
          - vim
          - git
          - ufw
          - fzf
        state: latest
        update_cache: true

    - name: UFW - Enable and deny by default
      community.general.ufw:
        state: enabled
        default: deny
